version: 0.2 
phases: 
  install: 
    runtime-versions:
      nodejs : 12 
    commands:
      - echo "Installing dependencies"
      - npm install 
      - npm install -g react
  build : 
    commands: 
      - echo "Building react project"
      - npm run build 
  post_build:
    commands: 
      - echo "Updating files in the S3 bucket"
      - aws s3 sync build/ s3://picture-perfect-s3-bucket --delete
  
